inputs:
    user: 
        description: 'Deploy user'
        required: true
    host: 
        description: 'Deploy host'
        required: true
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        -   ${{ inputs.user }}
        -   ${{ inputs.host }}
        -   ${{ inputs.port }}
        -   ${{ inputs.path }}
        -   ${{ inputs.owner }}
