name: 'Laravel Deploy'
description: 'Deploy Laravel Application to Server via SSH by RSync'
author: 'Hoang Ngoc Quy'
branding:
    icon: 'send'
    color: 'green'
inputs:
    user: 
        description: 'Deploy user'
        required: true
    host: 
        description: 'Deploy host'
        required: true
    port: 
        description: 'Deploy port'
        required: false
    owner: 
        description: 'Deploy owner'
        required: true

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        -   ${{ inputs.user }}
        -   ${{ inputs.host }}
        -   ${{ inputs.port }}
        -   ${{ inputs.path }}
        -   ${{ inputs.owner }}
